theme: minima
title: ARKLegalTech Talk
author: LDC-GKLAW
email: Ldc@gibsonkeithlaw.com
description: > # I'm a lawyer and a technophile. Let's talk legal tech.

# social links
twitter_username: ARKLegalTech # DO NOT include the @ character, or else the build will fail!
github_username:  LDC-GKLAW # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
